version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
  employee-record:
    image: employee-record:1.0
    container_name: employee-record
    ports:
      - 9090:8091
    links:
      - mymongodb