apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: employee-record
  name: employee-record
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: employee-record
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: employee-record
    spec:
      containers:
      - image: employee-record:1.0
        imagePullPolicy: ""
        name: employee-record
        ports:
        - containerPort: 8091
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
