apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vaccination-record
  name: vaccination-record
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vaccination-record
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: vaccination-record
    spec:
      containers:
      - image: rishaabh/vaccination-record:1.1
        imagePullPolicy: ""
        name: vaccination-record
        ports:
        - containerPort: 8092
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
